#!/usr/bin/env python3

import RPi.GPIO as GPIO
import time

Buzzer = 11  # Pin for the buzzer
TRIG = 11    # Pin for the ultrasonic sensor trigger
ECHO = 12    # Pin for the ultrasonic sensor echo

def setup():
    GPIO.setmode(GPIO.BOARD)
    GPIO.setup(Buzzer, GPIO.OUT)
    GPIO.setup(TRIG, GPIO.OUT)
    GPIO.setup(ECHO, GPIO.IN)

def distance():
    GPIO.output(TRIG, 0)
    time.sleep(0.000002)

    GPIO.output(TRIG, 1)
    time.sleep(0.00001)
    GPIO.output(TRIG, 0)

    while GPIO.input(ECHO) == 0:
        pass
    time1 = time.time()
    while GPIO.input(ECHO) == 1:
        pass
    time2 = time.time()

    during = time2 - time1
    return during * 340 / 2 * 100

def activate_buzzer():
    # Play a simple song when the distance is less than 1000 cm
    # You can add your song here or use the song data from your previous code
    # Example: song = [440, 523, 659, 784] for a simple melody
    song = [440, 523, 659, 784]
    beat = [0.5, 0.5, 0.5, 0.5]

    for i in range(len(song)):
        Buzz.ChangeFrequency(song[i])
        time.sleep(beat[i])

def loop():
    while True:
        dis = distance()
        print(dis, 'cm')
        
        if dis < 1000:
            activate_buzzer()
            print("Buzzer activated!")

        time.sleep(0.3)

def destroy():
    Buzz.stop()
    GPIO.output(Buzzer, 1)
    GPIO.cleanup()

if __name__ == "__main__":
    setup()
    Buzz = GPIO.PWM(Buzzer, 440)  # Initialize the buzzer
    try:
        loop()
    except KeyboardInterrupt:
        destroy()
